#!/bin/ash

# Copyright (c) 2016, Laird
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# contact: ews-support@lairdtech.com

# lighttpd - webserver init
# This init-script includes support for inetd.
#
# Usage:
# ./S??dcas {stop|start|restart}
#
# Invocation:
# ./S??dcas start
#


start() {
    echo "Starting dcas"
    /usr/bin/dcas | logger &
}

stop() {
    echo "Stopping dcas"
    killall dcas 2>/dev/null
  true
}

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  check) ## required for S??inetd pre-checking
    true
    ;;

  *)
    echo "Usage: ${0##*/} {stop|start|restart|check}"
    false
esac

exit $?
